const ADD_INGREDIENT = 'ADD_INGREDIENT';
const REMOVE_INGREDIENT ='REMOVE_INGREDIENT';
const INCREASE_TOTALPRICE ='INCREASE_TOTALPRICE';
const DECREASE_TOTALPRICE ='DECREASE_TOTALPRICE';
const RESET_INGREDIENT = 'RESET_INGREDIENT'



export {ADD_INGREDIENT,REMOVE_INGREDIENT,INCREASE_TOTALPRICE, DECREASE_TOTALPRICE, RESET_INGREDIENT}